                                          
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qasim Inayat
 */
public class TicketSearching extends javax.swing.JFrame {

    /**
     * Creates new form TicketSearching
     */
    public TicketSearching() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ClassjCB = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        TicketTypejCB = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        ChildrenjCB = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        AdultsjCB = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        TojCB = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        FromjCB = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        DatejCB = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ClassjL = new javax.swing.JLabel();
        ChildrenjL = new javax.swing.JLabel();
        TicketTypejL = new javax.swing.JLabel();
        AdultsjL = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        FromjL = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TojL = new javax.swing.JLabel();
        DatejL = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        TicketNojL = new javax.swing.JLabel();
        PricejL = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        RoutejL = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        SubTotaljL = new javax.swing.JLabel();
        TaxjL = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        TotaljL = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(86, 88, 89));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Nexa Bold", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OL Railway Management System");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Nexa Bold", 1, 75)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(86, 88, 89));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Class");

        ClassjCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Economy Class", "Business Class" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ticket Type");

        TicketTypejCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Single", "Return" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Children");

        ChildrenjCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Yes", "No" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Adults");

        AdultsjCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Yes" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("To");

        TojCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Karachi", "Islamabad", "Lahore", "Muree" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("From");

        FromjCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Muree", "Lahore", "Islamabad", "Karachi" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Date");

        DatejCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "23-Dec-15", "24-Dec-15", "25-Dec-15", "26-Dec-15", "27-Dec-15", "28-Dec-15", "29-Dec-15", "30-Dec-15", "31-Dec-15", "1-Jan-16", "2-Jan-16", "3-Jan-16", "4-Jan-16", "5-Jan-16", "6-Jan-16", "7-Jan-16", "8-Jan-16", "9-Jan-16", "10-Jan-16", "11-Jan-16", "12-Jan-16", "13-Jan-16", "14-Jan-16", "15-Jan-16" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ClassjCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TicketTypejCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ChildrenjCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AdultsjCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DatejCB, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(FromjCB, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(TojCB, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AdultsjCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ChildrenjCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TicketTypejCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ClassjCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(95, 95, 95)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TojCB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(FromjCB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(DatejCB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Class");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ticket Type");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Children");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Adults");

        ClassjL.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ClassjL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClassjL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        ChildrenjL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ChildrenjL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChildrenjL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        TicketTypejL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TicketTypejL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TicketTypejL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        AdultsjL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AdultsjL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdultsjL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("From");

        FromjL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FromjL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FromjL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("To");

        TojL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TojL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TojL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        DatejL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DatejL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DatejL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Date");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText(" Ticket No.");

        TicketNojL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TicketNojL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TicketNojL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        PricejL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PricejL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PricejL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Price");

        RoutejL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RoutejL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoutejL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Route");

        jPanel7.setBackground(new java.awt.Color(86, 88, 89));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Nexa Bold", 1, 45)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Information");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(86, 88, 89));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TojL, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FromjL, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DatejL, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(320, 320, 320))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addGap(80, 80, 80))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(88, 88, 88)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TicketNojL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RoutejL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PricejL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(ClassjL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TicketTypejL, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChildrenjL, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdultsjL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))))
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(TicketTypejL, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(ChildrenjL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AdultsjL, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(ClassjL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(119, 119, 119)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(FromjL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(TicketNojL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(TojL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(PricejL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(DatejL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(RoutejL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setText("Sub Total");

        SubTotaljL.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        SubTotaljL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubTotaljL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        TaxjL.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TaxjL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaxjL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("Tax");

        TotaljL.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TotaljL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotaljL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 88, 89), 3));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setText("Total");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel34)
                    .addComponent(jLabel36))
                .addGap(76, 76, 76)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TotaljL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TaxjL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SubTotaljL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGap(113, 113, 113)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(SubTotaljL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(TaxjL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(TotaljL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       totalButton();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clearButton();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketSearching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketSearching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketSearching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketSearching.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketSearching().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AdultsjCB;
    private javax.swing.JLabel AdultsjL;
    private javax.swing.JComboBox ChildrenjCB;
    private javax.swing.JLabel ChildrenjL;
    private javax.swing.JComboBox ClassjCB;
    private javax.swing.JLabel ClassjL;
    private javax.swing.JComboBox DatejCB;
    private javax.swing.JLabel DatejL;
    private javax.swing.JComboBox FromjCB;
    private javax.swing.JLabel FromjL;
    private javax.swing.JLabel PricejL;
    private javax.swing.JLabel RoutejL;
    private javax.swing.JLabel SubTotaljL;
    private javax.swing.JLabel TaxjL;
    private javax.swing.JLabel TicketNojL;
    private javax.swing.JComboBox TicketTypejCB;
    private javax.swing.JLabel TicketTypejL;
    private javax.swing.JComboBox TojCB;
    private javax.swing.JLabel TojL;
    private javax.swing.JLabel TotaljL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables

    public void totalButton()
    {
        if(
            ClassjCB.getSelectedItem().equals("") ||
            TicketTypejCB.getSelectedItem().equals("") ||
            ChildrenjCB.getSelectedItem().equals("") ||
            AdultsjCB.getSelectedItem().equals("") ||
            TojCB.getSelectedItem().equals("") ||
            FromjCB.getSelectedItem().equals("") ||
            DatejCB.getSelectedItem().equals("")
              
           )
        {
            JOptionPane.showMessageDialog(null, "Please Fill Properly");
            ClassjCB.setSelectedItem("");
            TicketTypejCB.setSelectedItem("");
            ChildrenjCB.setSelectedItem("");
            AdultsjCB.setSelectedItem("");
            TojCB.setSelectedItem("");
            FromjCB.setSelectedItem("");
            DatejCB.setSelectedItem("");
            RoutejL.setText("");
        }
        
        String To = TojCB.getSelectedItem().toString();
        String From = FromjCB.getSelectedItem().toString();
        String Class = ClassjCB.getSelectedItem().toString();
        
      
        if(To.contains("Karachi") && From.contains("Muree") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("12485");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
            
            
        }
        
        else if(To.contains("Karachi") && From.contains("Lahore") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("12800");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Karachi") && From.contains("Islamabad") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("12325");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        
        else if(To.contains("Karachi") && From.contains("Karachi") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("");
            TojL.setText("");
            FromjL.setText("");
            ClassjL.setText("");
            TicketTypejL.setText("");
            ChildrenjL.setText("");
            AdultsjL.setText("");
            DatejL.setText("");
            RoutejL.setText("");
            JOptionPane.showMessageDialog(null, "Fields are Same");
        }
        

        
        
        if(To.contains("Karachi") && From.contains("Muree") && Class.contains("Business Class"))
        {
            TicketNojL.setText("13485");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Karachi") && From.contains("Lahore") && Class.contains("Business Class"))
        {
            TicketNojL.setText("13800");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Karachi") && From.contains("Islamabad") && Class.contains("Business Class"))
        {
            TicketNojL.setText("13325");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Karachi") && From.contains("Karachi") && Class.contains("Business Class"))
        {
            TicketNojL.setText("");
            TojL.setText("");
            FromjL.setText("");
            ClassjL.setText("");
            JOptionPane.showMessageDialog(null, "Fields are Same");
        }
        
        
        
        
        
        if(To.contains("Islamabad") && From.contains("Karachi") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("15485");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Islamabad") && From.contains("Lahore") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("15800");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Islamabad") && From.contains("Muree") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("15325");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
       else if(To.contains("Islamabad") && From.contains("Islamabad") && Class.contains("Business Class"))
        {
            TicketNojL.setText("");
            TojL.setText("");
            FromjL.setText("");
            ClassjL.setText("");
            JOptionPane.showMessageDialog(null, "Fields are Same");
        }
        
        
        if(To.contains("Islamabad") && From.contains("Karachi") && Class.contains("Business Class"))
        {
            TicketNojL.setText("16485");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Islamabad") && From.contains("Lahore") && Class.contains("Business Class"))
        {
            TicketNojL.setText("16800");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Islamabad") && From.contains("Muree") && Class.contains("Business Class"))
        {
            TicketNojL.setText("16325");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Islamabad") && From.contains("Islamabad") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("");
            TojL.setText("");
            FromjL.setText("");
            ClassjL.setText("");
            JOptionPane.showMessageDialog(null, "Fields are Same");
        }
        
        
        
        
        if(To.contains("Lahore") && From.contains("Muree") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("17485");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Lahore") && From.contains("Islamabad") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("17800");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Lahore") && From.contains("Karachi") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("17325");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Lahore") && From.contains("Lahore") && Class.contains("Economy Class"))
        {
            
            TicketNojL.setText("");
            TojL.setText("");
            FromjL.setText("");
            ClassjL.setText("");
            JOptionPane.showMessageDialog(null, "Fields are Same");
        }
        
        
        
        if(To.contains("Lahore") && From.contains("Muree") && Class.contains("Business Class"))
        {
            TicketNojL.setText("18485");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Lahore") && From.contains("Islamabad") && Class.contains("Business Class"))
        {
            TicketNojL.setText("18800");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Lahore") && From.contains("Karachi") && Class.contains("Business Class"))
        {
            TicketNojL.setText("19325");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Lahore") && From.contains("Lahore") && Class.contains("Business Class"))
        {
            TicketNojL.setText("");
            TojL.setText("");
            FromjL.setText("");
            ClassjL.setText("");
            JOptionPane.showMessageDialog(null, "Fields are Same");
        }
        
        
        
        
        if(To.contains("Muree") && From.contains("Lahore") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("19485");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Muree") && From.contains("Islamabad") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("19800");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Muree") && From.contains("Karachi") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("19325");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Muree") && From.contains("Muree") && Class.contains("Economy Class"))
        {
            TicketNojL.setText("");
            TojL.setText("");
            FromjL.setText("");
            ClassjL.setText("");
            JOptionPane.showMessageDialog(null, "Fields are Same");
        }
        
        if(To.contains("Muree") && From.contains("Lahore") && Class.contains("Business Class"))
        {
            TicketNojL.setText("21485");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Muree") && From.contains("Islamabad") && Class.contains("Business Class"))
        {
            TicketNojL.setText("21800");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Muree") && From.contains("Karachi") && Class.contains("Business Class"))
        {
            TicketNojL.setText("21325");
            ClassjL.setText(ClassjCB.getSelectedItem().toString());
            TojL.setText(TojCB.getSelectedItem().toString());
            FromjL.setText(FromjCB.getSelectedItem().toString());
        }
        
        else if(To.contains("Muree") && From.contains("Muree") && Class.contains("Business Class"))
        {
            TicketNojL.setText("");
            TojL.setText("");
            FromjL.setText("");
            ClassjL.setText("");
            JOptionPane.showMessageDialog(null, "Fields are Same");
        
        }
        
        
        TicketTypejL.setText(TicketTypejCB.getSelectedItem().toString());
        ChildrenjL.setText(ChildrenjCB.getSelectedItem().toString());
        AdultsjL.setText(AdultsjCB.getSelectedItem().toString());
        DatejL.setText(DatejCB.getSelectedItem().toString());
        RoutejL.setText("Any");
        
        
        
        
        String TicketType = TicketTypejCB.getSelectedItem().toString();
        String Children = ChildrenjCB.getSelectedItem().toString();
        String _Class = ClassjCB.getSelectedItem().toString();
        BusinessLogic c = new BusinessLogic();
        if(TicketType.contains("Single") && Children.contains("No") && _Class.contains("Economy Class"))
        {
            
            int SubTotal = 1800;
            int Tax = 300;
           
            SubTotaljL.setText(SubTotal+"");
            TaxjL.setText(Tax+"");
            TotaljL.setText(c.single()+"");
            PricejL.setText("Rs. "+c.single());
            
            
        }
        
        if(TicketType.contains("Return") && Children.contains("No")&& _Class.contains("Economy Class") )
        {
            
            int SubTotal = 1800*2;
            int Tax = 300*2;
           
            SubTotaljL.setText(SubTotal+"");
            TaxjL.setText(Tax+"");
            TotaljL.setText(c.Return()+"");
            PricejL.setText("Rs. "+c.Return());   
        }
        
        if(TicketType.contains("Single") && Children.contains("Yes") && _Class.contains("Economy Class"))
        {
            
            int SubTotal = 1800*2;
            int Tax = 300;
           
            SubTotaljL.setText(SubTotal+"");
            TaxjL.setText(Tax+"");
            TotaljL.setText(c.Single_Children()+"");
            PricejL.setText("Rs. "+c.Single_Children());   
        }
        
        if(TicketType.contains("Return") && Children.contains("Yes") && _Class.contains("Economy Class"))
        {
            
            int SubTotal = 1800*4;
            int Tax = 600;
           
            SubTotaljL.setText(SubTotal+"");
            TaxjL.setText(Tax+"");
            TotaljL.setText(c.Return_Children()+"");
            PricejL.setText("Rs. "+c.Return_Children());   
        }
        
        
        
        BusinessLogicInherent d = new BusinessLogicInherent();
        if(TicketType.contains("Single") && Children.contains("No") && _Class.contains("Business Class"))
        {
            
            int SubTotal = 1800;
            int Tax = 300+1000;
           
            SubTotaljL.setText(SubTotal+"");
            TaxjL.setText(Tax+"");
            TotaljL.setText(d.singleBusiness()+"");
            PricejL.setText("Rs. "+d.singleBusiness());
            
            
        }
        
        if(TicketType.contains("Return") && Children.contains("No")&& _Class.contains("Business Class") )
        {
            
            int SubTotal = 1800*2;
            int Tax = 300*2+1000;
           
            SubTotaljL.setText(SubTotal+"");
            TaxjL.setText(Tax+"");
            TotaljL.setText(d.ReturnBusiness()+"");
            PricejL.setText("Rs. "+d.ReturnBusiness());   
        }
        
        if(TicketType.contains("Single") && Children.contains("Yes") && _Class.contains("Business Class"))
        {
            
            int SubTotal = 1800*2;
            int Tax = 300+1000;
           
            SubTotaljL.setText(SubTotal+"");
            TaxjL.setText(Tax+"");
            TotaljL.setText(d.Single_ChildrenBusiness()+"");
            PricejL.setText("Rs. "+d.Single_ChildrenBusiness());   
        }
        
        if(TicketType.contains("Return") && Children.contains("Yes") && _Class.contains("Business Class"))
        {
            
            int SubTotal = 1800*4;
            int Tax = 600+1000;
           
            SubTotaljL.setText(SubTotal+"");
            TaxjL.setText(Tax+"");
            TotaljL.setText(d.Return_ChildrenBusiness()+"");
            PricejL.setText("Rs. "+d.Return_ChildrenBusiness());   
        }
        
   }
    
    
    public void clearButton()
    {
        ClassjCB.setSelectedItem("");
        TicketTypejCB.setSelectedItem("");
        ChildrenjCB.setSelectedItem("");
        AdultsjCB.setSelectedItem("");
        TojCB.setSelectedItem("");
        FromjCB.setSelectedItem("");
        DatejCB.setSelectedItem("");
        SubTotaljL.setText("");
        TaxjL.setText("");
        TotaljL.setText("");
        ClassjL.setText("");
        TicketNojL.setText("");
        ChildrenjL.setText("");
        AdultsjL.setText("");
        FromjL.setText("");
        TojL.setText("");
        DatejL.setText("");
        TicketNojL.setText("");
        PricejL.setText("");
        RoutejL.setText("");
        TicketTypejL.setText("");
        
        
    }

}
